name: Test Email Notification

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Failing Step to Trigger Notification
        run: |
          echo "This step will fail."
          exit 1